<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#copylocallockfileassemblies -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <IsPackable>False</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppIdentity.Hosting" Version="0.14.1" />
    <PackageReference Include="CK.Cris.AspNet" Version="0.55.3--ci.1" />
    <PackageReference Include="CK.Cris.Auth" Version="0.43.2--ci.1" />
    <PackageReference Include="CK.Cris.Workspace" Version="15.1.2--ci.1" />
      
    <PackageReference Include="CK.DB.AspNet.Auth" Version="31.0.3--ci.5" />
    <PackageReference Include="CK.DB.User.NamedUser" Version="28.0.3--ci.1" />
    <PackageReference Include="CK.DB.User.PreferredCulture" Version="0.5.0--ci.7" />
    <PackageReference Include="CK.DB.User.UserPassword" Version="28.0.3--ci.5" />
    <PackageReference Include="CK.DB.Workspace" Version="15.1.2--ci.1" />
      
    <PackageReference Include="CK.Ng.AspNet.Auth.Basic" Version="0.31.3--ci.7" />
    <PackageReference Include="CK.Ng.Zorro.BackOffice" Version="0.7.0--ci.9" />
    <PackageReference Include="CK.Ng.Cris.AspNet.Auth" Version="0.55.3--ci.1" />
    <PackageReference Include="CK.Ng.UserProfile.PreferredCulture" Version="0.8.0--ci.12" />


      <PackageReference Include="CK.SqlServer.Dapper" Version="15.0.2--ci.1" />
    <PackageReference Include="CK.SqlServer.Transaction" Version="12.0.1" />

    <PackageReference Include="CK.UserManagement" Version="0.1.0--ci.22" />
    <PackageReference Include="CK.UserManagement.BinnedUser" Version="0.1.0--ci.22" />
    <PackageReference Include="CK.UserManagement.UserInvitation" Version="0.1.0--ci.22" />

    <ProjectReference Include="..\..\CK.Ng.Admin.UserManagement\CK.Ng.Admin.UserManagement.csproj" />
    <!--<ProjectReference Include="..\..\CK.Ng.Admin.UserManagement.BinnedUser\CK.Ng.Admin.UserManagement.BinnedUser.csproj" />-->
    <ProjectReference Include="..\..\CK.Ng.Admin.UserManagement.UserInvitation\CK.Ng.Admin.UserManagement.UserInvitation.csproj" />
    <ProjectReference Include="..\..\SLog.Mail.Branding\SLog.Mail.Branding.csproj" />
  </ItemGroup>
</Project>