<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.IO.UserManagement" Version="1.0.1--ci.3" />
        <PackageReference Include="CK.Ng.UserProfile.UserPassword.Reset" Version="1.0.1--ci.4" />
        <PackageReference Include="CK.Ng.Zorro.BackOffice" Version="1.0.1--ci.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CK.Ng.Admin\CK.Ng.Admin.csproj" />
    </ItemGroup>

</Project>
