<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.IO.UserManagement.UserBanned" Version="0.2.0--ci.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CK.Ng.Admin.UserManagement\CK.Ng.Admin.UserManagement.csproj" />
    </ItemGroup>

</Project>
