<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.IO.UserManagement.UserInvitation" Version="0.3.0--ci.6" />
        <PackageReference Include="CK.Ng.UserProfile.UserPassword.Lost" Version="0.9.0--ci.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CK.Ng.Admin.UserManagement\CK.Ng.Admin.UserManagement.csproj" />
    </ItemGroup>

</Project>
